
export const sitesConfig = [
  { id: "ACE",       label: "ACE" },
  { id: "RTG",       label: "RTG" },
  { id: "OWENDO",    label: "OWENDO" },
  { id: "NKOK",      label: "NKOK" },
  { id: "OYAN",      label: "OYAN" },
  { id: "BIFOUN",    label: "BIFOUN" },
  { id: "LAMBARENE", label: "LAMBARENE" },
  { id: "NTOUM",     label: "NTOUM" },
  { id: "NDJOLE",    label: "NDJOLE" },
  { id: "BOOUE",     label: "BOOUE" },
  { id: "MITZIC",    label: "MITZIC" },
  { id: "OYEM", label: "OYEM" },
  { id: "LASTOURVILLE", label: "LASTOURVILLE" },
  { id: "MOANDA", label: "MOANDA" },
  { id: "FRANCEVILLE", label: "FRANCEVILLE" },
  { id: "POG",       label: "POG" },
];

export const devicesIdConfig = [
  { device_id: "19",  hostname: "mpe-lbv10-01", site: "ACE"          },
  { device_id: "95",  hostname: "mpe-rtg10-01", site: "RTG"          },
  { device_id: "173", hostname: "edg-lbv10-01", site: "ACE"          },
  { device_id: "45",  hostname: "edg-rtg10-01", site: "RTG"          },
  { device_id: "181", hostname: "edg-owe10-01", site: "OWENDO"       },
  { device_id: "180", hostname: "edg-nko10-01", site: "NKOK"         },
  { device_id: "182", hostname: "edg-oya10-01", site: "OYAN"         },
  { device_id: "183", hostname: "edg-bif30-01", site: "BIFOUN"       },
  { device_id: "178", hostname: "edg-lam30-01", site: "LAMBARENE"    },
  { device_id: "249", hostname: "edg-nto10-01", site: "NTOUM"        },
  { device_id: "40",  hostname: "edg-njo30-01", site: "NDJOLE"       },
  { device_id: "248", hostname: "edg-boo60-01", site: "BOOUE"        },
  { device_id: "179", hostname: "edg-mit90-01", site: "MITZIC"       },
  { device_id: "185", hostname: "edg-oye90-01", site: "OYEM"         },
  { device_id: "43",  hostname: "edg-lav70-01", site: "LASTOURVILLE" },
  { device_id: "135", hostname: "edg-moa20-01", site: "MOANDA"       },
  { device_id: "44",  hostname: "edg-fcv20-01", site: "FRANCEVILLE"  },
  { device_id: "21",  hostname: "edg-pog80-01", site: "POG"          },
  { device_id: "231", hostname: "edg-pog80-02", site: "POG"          },
  { device_id: "230", hostname: "edg-pog80-03", site: "POG"          },
  //INTL---------------------------------------------------------
  { device_id: "20", hostname: "mpe-lis99-01", site: "INTL"          },
  { device_id: "247", hostname: "nce-rtg10-010308", site: "ACE"     },
  { device_id: "246", hostname: "nce-lbv10-012205", site: "ACE"    },
  { device_id: "209", hostname: "nce-lbv10-012206", site: "ACE"    },
  { device_id: "252", hostname: "nce-th275-083206", site: "Services"    },
  { device_id: "39", hostname: "nce-lis99-011114.bcb", site: "Services" },
];

export const devicesConfig = [
  { device_id: "19",  hostname: "mpe-lbv10-01", site: "ACE"          },
  { device_id: "95",  hostname: "mpe-rtg10-01", site: "RTG"          },
  { device_id: "173", hostname: "edg-lbv10-01", site: "ACE"          },
  { device_id: "45",  hostname: "edg-rtg10-01", site: "RTG"          },
  { device_id: "181", hostname: "edg-owe10-01", site: "OWENDO"       },
  { device_id: "180", hostname: "edg-nko10-01", site: "NKOK"         },
  { device_id: "182", hostname: "edg-oya10-01", site: "OYAN"         },
  { device_id: "183", hostname: "edg-bif30-01", site: "BIFOUN"       },
  { device_id: "178", hostname: "edg-lam30-01", site: "LAMBARENE"    },
  { device_id: "249", hostname: "edg-nto10-01", site: "NTOUM"        },
  { device_id: "40",  hostname: "edg-njo30-01", site: "NDJOLE"       },
  { device_id: "248", hostname: "edg-boo60-01", site: "BOOUE"        },
  { device_id: "179", hostname: "edg-mit90-01", site: "MITZIC"       },
  { device_id: "185", hostname: "edg-oye90-01", site: "OYEM"         },
  { device_id: "43",  hostname: "edg-lav70-01", site: "LASTOURVILLE" },
  { device_id: "135", hostname: "edg-moa20-01", site: "MOANDA"       },
  { device_id: "44",  hostname: "edg-fcv20-01", site: "FRANCEVILLE"  },
  { device_id: "21",  hostname: "edg-pog80-01", site: "POG"          },
  { device_id: "231", hostname: "edg-pog80-02", site: "POG"          },
  { device_id: "230", hostname: "edg-pog80-03", site: "POG"          },
  //INTL---------------------------------------------------------
  { device_id: "20", hostname: "mpe-lis99-01", site: "INTL"          },
  { device_id: "247", hostname: "nce-rtg10-010308", site: "ACE"     },
  { device_id: "246", hostname: "nce-lbv10-012205", site: "ACE"    },
  { device_id: "209", hostname: "nce-lbv10-012206", site: "ACE"    },
  { device_id: "252", hostname: "nce-th275-083206", site: "Services"    },
  { device_id: "39", hostname: "nce-lis99-011114.bcb", site: "Services" },
  { device_id: "Cap", hostname: "Cap", site: "Services" },
  { device_id: "Lag", hostname: "Lag", site: "Services" },
];

export const manualLinksConfig = [

  // ── ACE ↔ RTG ─────────────────────────────────────────────────────────────
  {
    link_id:       "L001",
    siteA:         "ACE", siteB:     "RTG",
    hostnameA:     "mpe-lbv10-01", hostnameB: "mpe-rtg10-01",
    portA_id:      "950",  portA_name: "1/2/1",
    portB_id:      "4226", portB_name: "1/1/1",
    capacity_gbps: 100,
  },
  {
    link_id:       "L002",
    siteA:         "ACE", siteB:     "RTG",
    hostnameA:     "edg-lbv10-01", hostnameB: "edg-rtg10-01",
    portA_id:      "9267",    portA_name: "GigabitEthernet0/3/6",
    portB_id:      "28041",    portB_name: "GigabitEthernet0/2/1",
    capacity_gbps: 10,
  },
  {
    link_id:       "L003",
    siteA:         "ACE", siteB:     "RTG",
    hostnameA:     "edg-lbv10-01", hostnameB: "edg-rtg10-01",
    portA_id:       "9274",    portA_name: "GigabitEthernet0/3/13",
    portB_id:      "28042",    portB_name: "GigabitEthernet0/2/2",
    capacity_gbps: 10,
  },

  // ── RTG ↔ OWENDO ──────────────────────────────────────────────────────────
  {
    link_id:       "L004",
    siteA:         "RTG", siteB:     "OWENDO",
    hostnameA:     "edg-rtg10-01", hostnameB: "edg-owe10-01",
    portA_id:      "2993",    portA_name: "GigabitEthernet0/3/6",
    portB_id:      "10776",    portB_name: "GigabitEthernet0/3/1",
    capacity_gbps: 10,
  },

  // ── RTG ↔ NTOUM ───────────────────────────────────────────────────────────
  {
    link_id:       "L005",
    siteA:         "RTG", siteB:     "NTOUM",
    hostnameA:     "edg-rtg10-01", hostnameB: "edg-nto10-01",
    portA_id:      "2980",    portA_name: "GigabitEthernet0/1/3",
    portB_id:      "26455",    portB_name: "GigabitEthernet0/3/6",
    capacity_gbps: 10,
  },
  {
    link_id:       "L006",
    siteA:         "RTG", siteB:     "NTOUM",
    hostnameA:     "edg-rtg10-01", hostnameB: "edg-nto10-01",
    portA_id:      "2981",    portA_name: "GigabitEthernet0/1/4",
    portB_id:      "26456",    portB_name: "GigabitEthernet0/3/7",
    capacity_gbps: 10,
  },
  {
    link_id:       "L007",
    siteA:         "RTG", siteB:     "NTOUM",
    hostnameA:     "edg-rtg10-01", hostnameB: "edg-nto10-01",
    portA_id:      "2977",    portA_name: "GigabitEthernet0/1/0",
    portB_id:      "26457",    portB_name: "GigabitEthernet0/3/8",
    capacity_gbps: 10,
  },
  {
    link_id:       "L008",
    siteA:         "RTG", siteB:     "NTOUM",
    hostnameA:     "edg-rtg10-01", hostnameB: "edg-nto10-01",
    portA_id:      "2983",    portA_name: "GigabitEthernet0/1/6",
    portB_id:      "26460",    portB_name: "GigabitEthernet0/3/11",
    capacity_gbps: 10,
  },
  {
    link_id:       "L009",
    siteA:         "RTG", siteB:     "NTOUM",
    hostnameA:     "edg-rtg10-01", hostnameB: "edg-nto10-01",
    portA_id:      "28040",    portA_name: "GigabitEthernet0/2/0",
    portB_id:      "26443",    portB_name: "GigabitEthernet0/1/4",
    capacity_gbps: 10,
  },
  {
    link_id:       "L010",
    siteA:         "RTG", siteB:     "NTOUM",
    hostnameA:     "edg-rtg10-01", hostnameB: "edg-nto10-01",
    portA_id:      "40705",    portA_name: "GigabitEthernet0/1/9",
    portB_id:      "26441",    portB_name: "GigabitEthernet0/1/2",
    capacity_gbps: 10,
  },
  {
    link_id:       "L011",
    siteA:         "RTG", siteB:     "NTOUM",
    hostnameA:     "edg-rtg10-01", hostnameB: "edg-nto10-01",
    portA_id:      "2990",    portA_name: "100GE0/3/3",
    portB_id:      "26449",    portB_name: "100GE0/3/0",
    capacity_gbps: 100,
  },

  // ── OWENDO ↔ NKOK ─────────────────────────────────────────────────────────
  {
    link_id:       "L012",
    siteA:         "OWENDO", siteB:     "NKOK",
    hostnameA:     "edg-owe10-01", hostnameB: "edg-nko10-01",
    portA_id:      "10773",    portA_name: "GigabitEthernet0/3/0",
    portB_id:      "10733",    portB_name: "GigabitEthernet0/3/1",
    capacity_gbps: 10,
  },

  // ── NKOK ↔ NTOUM ──────────────────────────────────────────────────────────
  {
    link_id:       "L013",
    siteA:         "NKOK", siteB:     "NTOUM",
    hostnameA:     "edg-nko10-01", hostnameB: "edg-nto10-01",
    portA_id:      "10732",    portA_name: "GigabitEthernet0/3/0",
    portB_id:      "26459",    portB_name: "GigabitEthernet0/3/10",
    capacity_gbps: 10,
  },

  // ── OYAN ↔ BIFOUN ─────────────────────────────────────────────────────────
  {
    link_id:       "L014",
    siteA:         "OYAN", siteB:     "BIFOUN",
    hostnameA:     "edg-oya10-01", hostnameB: "edg-bif30-01",
    portA_id:      "10809",    portA_name: "GigabitEthernet0/3/5",
    portB_id:      "10781",    portB_name: "GigabitEthernet0/3/0",
    capacity_gbps: 10,
  },
  {
    link_id:       "L015",
    siteA:         "OYAN", siteB:     "BIFOUN",
    hostnameA:     "edg-oya10-01", hostnameB: "edg-bif30-01",
    portA_id:      "10815",    portA_name: "GigabitEthernet0/3/7",
    portB_id:      "15722",    portB_name: "GigabitEthernet0/2/1",
    capacity_gbps: 10,
  },

  // ── BIFOUN ↔ LAMBARENE ────────────────────────────────────────────────────
  {
    link_id:       "L016",
    siteA:         "BIFOUN", siteB:     "LAMBARENE",
    hostnameA:     "edg-bif30-01", hostnameB: "edg-lam30-01",
    portA_id:      "10784",    portA_name: "GigabitEthernet0/3/1",
    portB_id:      "10669",    portB_name: "GigabitEthernet0/2/1",
    capacity_gbps: 10,
  },
  {
    link_id:       "L017",
    siteA:         "BIFOUN", siteB:     "LAMBARENE",
    hostnameA:     "edg-bif30-01", hostnameB: "edg-lam30-01",
    portA_id:      "30258",    portA_name: "GigabitEthernet0/1/0",
    portB_id:      "10671",    portB_name: "GigabitEthernet0/2/3",
    capacity_gbps: 10,
  },

  // ── LAMBARENE ↔ NDJOLE ────────────────────────────────────────────────────
  {
    link_id:       "L018",
    siteA:         "LAMBARENE", siteB:     "NDJOLE",
    hostnameA:     "edg-lam30-01", hostnameB: "edg-njo30-01",
    portA_id:      "33702",    portA_name: "GigabitEthernet0/2/0",
    portB_id:      "2658",    portB_name: "GigabitEthernet0/3/10",
    capacity_gbps: 10,
  },
  {
    link_id:       "L019",
    siteA:         "LAMBARENE", siteB:     "NDJOLE",
    hostnameA:     "edg-lam30-01", hostnameB: "edg-njo30-01",
    portA_id:      "10670",    portA_name: "GigabitEthernet0/2/2",
    portB_id:      "2659",    portB_name: "GigabitEthernet0/3/11",
    capacity_gbps: 10,
  },
  {
    link_id:       "L020",
    siteA:         "LAMBARENE", siteB:     "NDJOLE",
    hostnameA:     "edg-lam30-01", hostnameB: "edg-njo30-01",
    portA_id:      "10675",    portA_name: "GigabitEthernet0/2/7",
    portB_id:      "2643",    portB_name: "GigabitEthernet0/1/5",
    capacity_gbps: 10,
  },

  // ── NTOUM ↔ OYAN ──────────────────────────────────────────────────────────
  {
    link_id:       "L021",
    siteA:         "NTOUM", siteB:     "OYAN",
    hostnameA:     "edg-nto10-01", hostnameB: "edg-oya10-01",
    portA_id:      "26444",    portA_name: "GigabitEthernet0/1/5",
    portB_id:      "10811",    portB_name: "GigabitEthernet0/3/6",
    capacity_gbps: 10,
  },
  {
    link_id:       "L022",
    siteA:         "NTOUM", siteB:     "OYAN",
    hostnameA:     "edg-nto10-01", hostnameB: "edg-oya10-01",
    portA_id:      "26445",    portA_name: "GigabitEthernet0/1/6",
    portB_id:      "10806",    portB_name: "GigabitEthernet0/3/4",
    capacity_gbps: 10,
  },

  // ── NTOUM ↔ NDJOLE ────────────────────────────────────────────────────────
  {
    link_id:       "L023",
    siteA:         "NTOUM", siteB:     "NDJOLE",
    hostnameA:     "edg-nto10-01", hostnameB: "edg-njo30-01",
    portA_id:      "26442",    portA_name: "GigabitEthernet0/1/3",
    portB_id:      "2660",    portB_name: "GigabitEthernet0/3/12",
    capacity_gbps: 10,
  },
  {
    link_id:       "L024",
    siteA:         "NTOUM", siteB:     "NDJOLE",
    hostnameA:     "edg-nto10-01", hostnameB: "edg-njo30-01",
    portA_id:      "26447",    portA_name: "GigabitEthernet0/1/8",
    portB_id:      "2655",    portB_name: "GigabitEthernet0/3/7",
    capacity_gbps: 10,
  },
  {
    link_id:       "L025",
    siteA:         "NTOUM", siteB:     "NDJOLE",
    hostnameA:     "edg-nto10-01", hostnameB: "edg-njo30-01",
    portA_id:      "26448",    portA_name: "GigabitEthernet0/1/9",
    portB_id:      "2641",    portB_name: "GigabitEthernet0/1/3",
    capacity_gbps: 10,
  },
  {
    link_id:       "L026",
    siteA:         "NTOUM", siteB:     "NDJOLE",
    hostnameA:     "edg-nto10-01", hostnameB: "edg-njo30-01",
    portA_id:      "26453",    portA_name: "GigabitEthernet0/3/4",
    portB_id:      "2654",    portB_name: "GigabitEthernet0/3/6",
    capacity_gbps: 10,
  },
  {
    link_id:       "L027",
    siteA:         "NTOUM", siteB:     "NDJOLE",
    hostnameA:     "edg-nto10-01", hostnameB: "edg-njo30-01",
    portA_id:      "26458",    portA_name: "GigabitEthernet0/3/9",
    portB_id:      "2656",    portB_name: "GigabitEthernet0/3/8",
    capacity_gbps: 10,
  },
  {
    link_id:       "L028",
    siteA:         "NTOUM", siteB:     "NDJOLE",
    hostnameA:     "edg-nto10-01", hostnameB: "edg-njo30-01",
    portA_id:      "26461",    portA_name: "GigabitEthernet0/3/12",
    portB_id:      "2642",    portB_name: "GigabitEthernet0/1/4",
    capacity_gbps: 10,
  },
  {
    link_id:       "L029",
    siteA:         "NTOUM", siteB:     "NDJOLE",
    hostnameA:     "edg-nto10-01", hostnameB: "edg-njo30-01",
    portA_id:      "26462",    portA_name: "GigabitEthernet0/3/13",
    portB_id:      "2661",    portB_name: "GigabitEthernet0/3/13",
    capacity_gbps: 10,
  },

  // ── NDJOLE ↔ BOOUE ────────────────────────────────────────────────────────
  {
    link_id:       "L030",
    siteA:         "NDJOLE", siteB:     "BOOUE",
    hostnameA:     "edg-njo30-01", hostnameB: "edg-boo60-01",
    portA_id:      "2638",    portA_name: "GigabitEthernet0/1/0",
    portB_id:      "26380",    portB_name: "GigabitEthernet0/3/12",
    capacity_gbps: 10,
  },
  {
    link_id:       "L031",
    siteA:         "NDJOLE", siteB:     "BOOUE",
    hostnameA:     "edg-njo30-01", hostnameB: "edg-boo60-01",
    portA_id:      "2639",    portA_name: "GigabitEthernet0/1/1",
    portB_id:      "26381",    portB_name: "GigabitEthernet0/3/13",
    capacity_gbps: 10,
  },
  {
    link_id:       "L032",
    siteA:         "NDJOLE", siteB:     "BOOUE",
    hostnameA:     "edg-njo30-01", hostnameB: "edg-boo60-01",
    portA_id:      "2640",    portA_name: "GigabitEthernet0/1/2",
    portB_id:      "26374",    portB_name: "GigabitEthernet0/3/6",
    capacity_gbps: 10,
  },
  {
    link_id:       "L033",
    siteA:         "NDJOLE", siteB:     "BOOUE",
    hostnameA:     "edg-njo30-01", hostnameB: "edg-boo60-01",
    portA_id:      "2652",    portA_name: "GigabitEthernet0/3/4",
    portB_id:      "26375",    portB_name: "GigabitEthernet0/3/7",
    capacity_gbps: 10,
  },
  {
    link_id:       "L034",
    siteA:         "NDJOLE", siteB:     "BOOUE",
    hostnameA:     "edg-njo30-01", hostnameB: "edg-boo60-01",
    portA_id:      "2653",    portA_name: "GigabitEthernet0/3/5",
    portB_id:      "26376",    portB_name: "GigabitEthernet0/3/8",
    capacity_gbps: 10,
  },
  {
    link_id:       "L035",
    siteA:         "NDJOLE", siteB:     "BOOUE",
    hostnameA:     "edg-njo30-01", hostnameB: "edg-boo60-01",
    portA_id:      "2657",    portA_name: "GigabitEthernet0/3/9",
    portB_id:      "26366",    portB_name: "GigabitEthernet0/1/8",
    capacity_gbps: 10,
  },

  // ── BOOUE ↔ MITZIC ────────────────────────────────────────────────────────
  {
    link_id:       "L036",
    siteA:         "BOOUE", siteB:     "MITZIC",
    hostnameA:     "edg-boo60-01", hostnameB: "edg-mit90-01",
    portA_id:      "38322",    portA_name: "GigabitEthernet0/2/0",
    portB_id:      "10722",    portB_name: "GigabitEthernet0/3/10",
    capacity_gbps: 10,
  },
  {
    link_id:       "L037",
    siteA:         "BOOUE", siteB:     "MITZIC",
    hostnameA:     "edg-boo60-01", hostnameB: "edg-mit90-01",
    portA_id:      "26378",    portA_name: "GigabitEthernet0/3/10",
    portB_id:      "10717",    portB_name: "GigabitEthernet0/3/5",
    capacity_gbps: 10,
  },
  {
    link_id:       "L038",
    siteA:         "BOOUE", siteB:     "MITZIC",
    hostnameA:     "edg-boo60-01", hostnameB: "edg-mit90-01",
    portA_id:      "26379",    portA_name: "GigabitEthernet0/3/11",
    portB_id:      "10716",    portB_name: "GigabitEthernet0/3/4",
    capacity_gbps: 10,
  },
  // ── MITZIC ↔ OYEM ────────────────────────────────────────────────────────
  {
    link_id: "L039",
    siteA: "MITZIC",
    siteB: "OYEM",
    portA_id: "10718",
    portA_name: "GigabitEthernet0/3/6",
    portB_id: "10908",
    portB_name: "GigabitEthernet0/3/4",
    hostnameA: "edg-mit90-01",
    hostnameB: "edg-oye90-01",
    capacity_gbps: 10,
  },
   {
    link_id: "L040",
    siteA: "MITZIC",
    siteB: "OYEM",
    portA_id: "10719",
    portA_name: "GigabitEthernet0/3/7",
    portB_id: "10909",
    portB_name: "GigabitEthernet0/3/5",
    hostnameA: "edg-mit90-01",
    hostnameB: "edg-oye90-01",
    capacity_gbps: 10,
  },
   // =========================
  // BOOUE <-> LASTOURVILLE
  // =========================
  {
    link_id: "L041",
    siteA: "BOOUE",
    siteB: "LASTOURVILLE",
    portA_id: "26360",
    portA_name: "GigabitEthernet0/1/2",
    portB_id: "2792",
    portB_name: "GigabitEthernet0/3/10",
    hostnameA: "edg-boo60-01",
    hostnameB: "edg-lav70-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L042",
    siteA: "BOOUE",
    siteB: "LASTOURVILLE",
    portA_id: "26361",
    portA_name: "GigabitEthernet0/1/3",
    portB_id: "2793",
    portB_name: "GigabitEthernet0/3/11",
    hostnameA: "edg-boo60-01",
    hostnameB: "edg-lav70-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L043",
    siteA: "BOOUE",
    siteB: "LASTOURVILLE",
    portA_id: "26365",
    portA_name: "GigabitEthernet0/1/7",
    portB_id: "2775",
    portB_name: "GigabitEthernet0/1/3",
    hostnameA: "edg-boo60-01",
    hostnameB: "edg-lav70-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L044",
    siteA: "BOOUE",
    siteB: "LASTOURVILLE",
    portA_id: "26367",
    portA_name: "GigabitEthernet0/1/9",
    portB_id: "2778",
    portB_name: "GigabitEthernet0/1/6",
    hostnameA: "edg-boo60-01",
    hostnameB: "edg-lav70-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L045",
    siteA: "BOOUE",
    siteB: "LASTOURVILLE",
    portA_id: "26372",
    portA_name: "GigabitEthernet0/3/4",
    portB_id: "2788",
    portB_name: "GigabitEthernet0/3/6",
    hostnameA: "edg-boo60-01",
    hostnameB: "edg-lav70-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L046",
    siteA: "BOOUE",
    siteB: "LASTOURVILLE",
    portA_id: "26373",
    portA_name: "GigabitEthernet0/3/5",
    portB_id: "2776",
    portB_name: "GigabitEthernet0/1/4",
    hostnameA: "edg-boo60-01",
    hostnameB: "edg-lav70-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L047",
    siteA: "BOOUE",
    siteB: "LASTOURVILLE",
    portA_id: "26377",
    portA_name: "GigabitEthernet0/3/9",
    portB_id: "2790",
    portB_name: "GigabitEthernet0/3/8",
    hostnameA: "edg-boo60-01",
    hostnameB: "edg-lav70-01",
    capacity_gbps: 10,
  },

  // =========================
  // LASTOURVILLE <-> MOANDA
  // =========================
  {
    link_id: "L048",
    siteA: "LASTOURVILLE",
    siteB: "MOANDA",
    portA_id: "2777",
    portA_name: "GigabitEthernet0/1/5",
    portB_id: "4680",
    portB_name: "GigabitEthernet0/3/7",
    hostnameA: "edg-lav70-01",
    hostnameB: "edg-moa20-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L049",
    siteA: "LASTOURVILLE",
    siteB: "MOANDA",
    portA_id: "2779",
    portA_name: "GigabitEthernet0/1/7",
    portB_id: "4669",
    portB_name: "GigabitEthernet0/1/6",
    hostnameA: "edg-lav70-01",
    hostnameB: "edg-moa20-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L050",
    siteA: "LASTOURVILLE",
    siteB: "MOANDA",
    portA_id: "2780",
    portA_name: "GigabitEthernet0/1/8",
    portB_id: "4670",
    portB_name: "GigabitEthernet0/1/7",
    hostnameA: "edg-lav70-01",
    hostnameB: "edg-moa20-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L051",
    siteA: "LASTOURVILLE",
    siteB: "MOANDA",
    portA_id: "2786",
    portA_name: "GigabitEthernet0/3/4",
    portB_id: "4679",
    portB_name: "GigabitEthernet0/3/6",
    hostnameA: "edg-lav70-01",
    hostnameB: "edg-moa20-01",
    capacity_gbps: 10,
  },
   {
    link_id: "L052",
    siteA: "LASTOURVILLE",
    siteB: "MOANDA",
    portA_id: "2791",
    portA_name: "GigabitEthernet0/3/9",
    portB_id: "4682",
    portB_name: "GigabitEthernet0/3/9",
    hostnameA: "edg-lav70-01",
    hostnameB: "edg-moa20-01",
    capacity_gbps: 10,
  },
   {
    link_id: "L053",
    siteA: "LASTOURVILLE",
    siteB: "MOANDA",
    portA_id: "2794",
    portA_name: "GigabitEthernet0/3/12",
    portB_id: "4677",
    portB_name: "GigabitEthernet0/3/4",
    hostnameA: "edg-lav70-01",
    hostnameB: "edg-moa20-01",
    capacity_gbps: 10,
  },
   {
    link_id: "L054",
    siteA: "LASTOURVILLE",
    siteB: "MOANDA",
    portA_id: "2795",
    portA_name: "GigabitEthernet0/3/13",
    portB_id: "4686",
    portB_name: "GigabitEthernet0/3/13",
    hostnameA: "edg-lav70-01",
    hostnameB: "edg-moa20-01",
    capacity_gbps: 10,
  },

  // =========================
  // MOANDA <-> FRANCEVILLE
  // =========================
  {
    link_id: "L055",
    siteA: "MOANDA",
    siteB: "FRANCEVILLE",
    portA_id: "4673",
    portA_name: "100GE0/3/0",
    portB_id: "2813",
    portB_name: "100GE0/3/0",
    hostnameA: "edg-moa20-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 100,
  },
  {
    link_id: "L056",
    siteA: "MOANDA",
    siteB: "FRANCEVILLE",
    portA_id: "4671",
    portA_name: "GigabitEthernet0/1/8",
    portB_id: "2810",
    portB_name: "GigabitEthernet0/1/7",
    hostnameA: "edg-moa20-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L057",
    siteA: "MOANDA",
    siteB: "FRANCEVILLE",
    portA_id: "4672",
    portA_name: "GigabitEthernet0/1/9",
    portB_id: "2809",
    portB_name: "GigabitEthernet0/1/6",
    hostnameA: "edg-moa20-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L058",
    siteA: "MOANDA",
    siteB: "FRANCEVILLE",
    portA_id: "4678",
    portA_name: "GigabitEthernet0/3/5",
    portB_id: "2820",
    portB_name: "GigabitEthernet0/3/7",
    hostnameA: "edg-moa20-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L059",
    siteA: "MOANDA",
    siteB: "FRANCEVILLE",
    portA_id: "4683",
    portA_name: "GigabitEthernet0/3/10",
    portB_id: "2821",
    portB_name: "GigabitEthernet0/3/8",
    hostnameA: "edg-moa20-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L060",
    siteA: "MOANDA",
    siteB: "FRANCEVILLE",
    portA_id: "4684",
    portA_name: "GigabitEthernet0/3/11",
    portB_id: "2819",
    portB_name: "GigabitEthernet0/3/6",
    hostnameA: "edg-moa20-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L061",
    siteA: "MOANDA",
    siteB: "FRANCEVILLE",
    portA_id: "4685",
    portA_name: "GigabitEthernet0/3/12",
    portB_id: "2825",
    portB_name: "GigabitEthernet0/3/12",
    hostnameA: "edg-moa20-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },

  // =========================
  // ACE <-> FRANCEVILLE
  // =========================
  {
    link_id: "L062",
    siteA: "ACE",
    siteB: "FRANCEVILLE",
    portA_id: "9251",
    portA_name: "GigabitEthernet0/1/0",
    portB_id: "2808",
    portB_name: "GigabitEthernet0/1/5",
    hostnameA: "edg-lbv10-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L063",
    siteA: "ACE",
    siteB: "FRANCEVILLE",
    portA_id: "9252",
    portA_name: "GigabitEthernet0/1/1",
    portB_id: "2822",
    portB_name: "GigabitEthernet0/3/9",
    hostnameA: "edg-lbv10-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },

  {
    link_id: "L064",
    siteA: "ACE",
    siteB: "FRANCEVILLE",
    portA_id: "9270",
    portA_name: "GigabitEthernet0/3/9",
    portB_id: "2824",
    portB_name: "GigabitEthernet0/3/11",
    hostnameA: "edg-lbv10-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },
  {
    link_id: "L065",
    siteA: "ACE",
    siteB: "FRANCEVILLE",
    portA_id: "9271",
    portA_name: "GigabitEthernet0/3/10",
    portB_id: "2817",
    portB_name: "GigabitEthernet0/3/4",
    hostnameA: "edg-lbv10-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },
    {
    link_id: "L066",
    siteA: "ACE",
    siteB: "FRANCEVILLE",
    portA_id: "9272",
    portA_name: "GigabitEthernet0/3/11",
    portB_id: "2818",
    portB_name: "GigabitEthernet0/3/5",
    hostnameA: "edg-lbv10-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },
    {
    link_id: "L067",
    siteA: "ACE",
    siteB: "FRANCEVILLE",
    portA_id: "9273",
    portA_name: "GigabitEthernet0/3/12",
    portB_id: "2826",
    portB_name: "GigabitEthernet0/3/13",
    hostnameA: "edg-lbv10-01",
    hostnameB: "edg-fcv20-01",
    capacity_gbps: 10,
  },

  // ── ACE ↔ POG ─────────────────────────────────────────────────────────────
{
  link_id:       "L0068",
  siteA:         "ACE",
  siteB:         "POG",
  hostnameA:     "mpe-lbv10-01",
  hostnameB:     "edg-pog80-01",
  portA_id:      "431",
  portA_name:    "1/1/1",
  portB_id:      "19885",
  portB_name:    "100GE0/3/0",
  capacity_gbps: 100,
},
{
  link_id:       "L071",
  siteA:         "ACE",
  siteB:         "POG",
  hostnameA:     "edg-lbv10-01",
  hostnameB:     "edg-pog80-01",
  portA_id:      "9258",
  portA_name:    "GigabitEthernet0/1/7",
  portB_id:      "19890",
  portB_name:    "GigabitEthernet0/3/5",
  capacity_gbps: 10,
},
{
  link_id:       "L069",
  siteA:         "ACE",
  siteB:         "POG",
  hostnameA:     "edg-lbv10-01",
  hostnameB:     "edg-pog80-01",
  portA_id:      "9259",
  portA_name:    "GigabitEthernet0/1/8",
  portB_id:      "19889",
  portB_name:    "GigabitEthernet0/3/4",
  capacity_gbps: 10,
},
{
  link_id:       "L070",
  siteA:         "ACE",
  siteB:         "POG",
  hostnameA:     "edg-lbv10-01",
  hostnameB:     "edg-pog80-01",
  portA_id:      "9260",
  portA_name:    "GigabitEthernet0/1/9",
  portB_id:      "19884",
  portB_name:    "GigabitEthernet0/1/9",
  capacity_gbps: 10,
},

// ── RTG ↔ POG ─────────────────────────────────────────────────────────────
{
  link_id:       "L072",
  siteA:         "ACE",
  siteB:         "POG",
  hostnameA:     "mpe-rtg10-01",
  hostnameB:     "edg-pog80-03",
  portA_id:      "26519",
  portA_name:    "3/1/2",
  portB_id:      "20370",
  portB_name:    "100GE0/3/0",
  capacity_gbps: 100,
},

// ── POG ↔ POG (inter-équipements sur le même site POG) ────────────────────
{
  link_id:       "L073",
  siteA:         "ACE",
  siteB:         "POG",
  hostnameA:     "edg-pog80-01",
  hostnameB:     "edg-pog80-03",
  portA_id:      "19887",
  portA_name:    "100GE0/3/2",
  portB_id:      "20371",
  portB_name:    "100GE0/3/1",
  capacity_gbps: 100,
},
{
  link_id:       "L074",
  siteA:         "ACE",
  siteB:         "POG",
  hostnameA:     "edg-pog80-01",
  hostnameB:     "edg-pog80-02",
  portA_id:      "19892",
  portA_name:    "GigabitEthernet0/3/7",
  portB_id:      "20449",
  portB_name:    "GigabitEthernet0/2/0",
  capacity_gbps: 10,
},
{
  link_id:       "L075",
  siteA:         "ACE",
  siteB:         "POG",
  hostnameA:     "edg-pog80-01",
  hostnameB:     "edg-pog80-02",
  portA_id:      "19891",
  portA_name:    "GigabitEthernet0/3/6",
  portB_id:      "20422",
  portB_name:    "GigabitEthernet0/3/0",
  capacity_gbps: 10,
},

// ── LIENS INTERNATIONAUX ────────────────────
{
  link_id:       "L077",
  siteA:         "ACE",
  siteB:         "INTL",
  hostnameA:     "mpe-lbv10-01",
  hostnameB:     "mpe-lis99-01",
  portA_id:      "19674",
  portA_name:    "2/1/3",
  portB_id:      "1109",
  portB_name:    "1/2/5",
  capacity_gbps: 100,
},
{
  link_id:       "L078",
  siteA:         "ACE",
  siteB:         "INTL",
  hostnameA:     "mpe-lbv10-01",
  hostnameB:     "mpe-lis99-01",
  portA_id:      "19675",
  portA_name:    "2/1/4",
  portB_id:      "1110",
  portB_name:    "1/2/6",
  capacity_gbps: 10,
},
{
  link_id:       "L079",
  siteA:         "ACE",
  siteB:         "INTL",
  hostnameA:     "mpe-lbv10-01",
  hostnameB:     "mpe-lis99-01",
  portA_id:      "19676",
  portA_name:    "2/1/5",
  portB_id:      "1112",
  portB_name:    "1/2/8",
  capacity_gbps: 10,
},
{
  link_id:       "L080",
  siteA:         "ACE",
  siteB:         "INTL",
  hostnameA:     "mpe-lbv10-01",
  portA_id:      "19679",
  portA_name:    "2/1/8",
  hostnameB:     "mpe-lis99-01",
  portB_id:      "1105",
  portB_name:    "1/2/1",
  capacity_gbps: 10,
},

 // ── RTG ↔ LIS ─────────────────────────────────────────────────────────────
  {
    link_id:       "L081",
    siteA:         "ACE", siteB:     "INTL",
    hostnameA:     "mpe-rtg10-01", hostnameB: "mpe-lis99-01",
    portA_id:      "19814",  portA_name: "2/1/7",
    portB_id:      "1108", portB_name: "1/2/4",
    capacity_gbps: 10,
  },
   //------------------Lien vers Paris--------------------
   {
    link_id:       "L700",
    siteA:         "ACE", siteB:     "INTL",
    hostnameA:     "mpe-lbv10-01", hostnameB: "pbb-th275",
    portA_id:      " 19680",  portA_name: "2/1/9",
    portB_id:      "2809", portB_name: "pbb-th275",
    capacity_gbps: 10,
  },
   //------------------Lien vers ORANGE--------------------
   {
    link_id:       "L700",
    siteA:         "ACE", siteB:     "INTL",
    hostnameA:     "mpe-lbv10-01", hostnameB: "pbb-th275",
    portA_id:      " 19681",  portA_name: "2/1/10",
    portB_id:      "", portB_name: "Orange",
    capacity_gbps: 10,
  },
//------------------Les Servicess TH2--------------------
 {
    link_id:       "L082",
    siteA:         "ACE", siteB:     "Services",
    hostnameA:     "nce-lbv10-012206", hostnameB: "nce-th275-083206",
    portA_id:      " 20134",  portA_name: "ACCESS PORT-1-1-3-1",
    portB_id:      "28039", portB_name: "ACCESS PORT-1-1-2-1",
    capacity_gbps: 10,
  },
  //------------------Les Servicess--------------------
   {
    link_id:       "L083",
    siteA:         "ACE", siteB:     "Services",
    hostnameA:     "nce-lbv10-012206", hostnameB: "nce-lis99-011114.bcb",
    portA_id:      "20133",  portA_name: "ACCESS PORT-1-1-2-1",
    portB_id:      "2624", portB_name: "ACCESS PORT-1-1-3-1",
    capacity_gbps: 10,
  },

  {
    link_id:       "L084",
    siteA:         "ACE", siteB:     "Services",
    hostnameA:     "nce-rtg10-010308", hostnameB: "nce-lis99-011114.bcb",
    portA_id:      "26348",  portA_name: "ACCESS PORT-1-1-2-1",
    portB_id:      "2616", portB_name: "ACCESS PORT-1-1-2-1",
    capacity_gbps: 10,
  },
  //------------------Servicess LAGOS--------------------
   {
  link_id:       "L701",
  siteA:         "ACE",
  siteB:         "Services",
  hostnameA:     "edg-lbv10-01",
  hostnameB:     "Lagos",
  portA_id:      "33759",
  portA_name:    "GigabitEthernet0/2/1",
  portB_id:      "",
  portB_name:    "Lagos",
  capacity_gbps: 10,
},
//------------------Servicess CAPTOWN--------------------
{
    link_id:       "L702",
    siteA:         "ACE", siteB: "Services",
    hostnameA:     "nce-lbv10-012205", hostnameB: "Cap",
    portA_id:      "24919",  portA_name: "ACCESS PORT-1-1-2-1",
    portB_id:      "", portB_name: "Cap",
    capacity_gbps: 10,
  },

  //------------------GBMA SAOTOME--------------------
{
    link_id:       "L703",
    siteA:         "ACE", siteB: "Services",
    hostnameA:     "mpe-lbv10-01", hostnameB: "SAOTOME",
    portA_id:      "19744",  portA_name: "3/2/13",
    portB_id:      "", portB_name: "GBMA-IXEN-19213177-150M",
    capacity_gbps: 10,
  },
];